name: Test Deploy K8s Script

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Installer Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Exécuter le script de déploiement (simulation)
        run: |
          echo "# ATTENTION : Ce script installe k3s, helm et modifie le système."
          echo "# Pour un vrai test, décommente la ligne suivante :"
          sudo python3 deploy.py
